image: Visual Studio 2019
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule --quiet update --init --recursive
platform:
  - x64
configuration:
  - Release
build:
  project: Solution\Menyoo.sln
  verbosity: minimal
after_build:
  - 7z -tzip a MenyooSP.zip %APPVEYOR_BUILD_FOLDER%\Solution\source\_Build\bin\Release\* -xr!*.map -xr!Trash
artifacts:
  - path: MenyooSP.zip
    name: Latest build of MenyooSP