/*
* Menyoo PC - Grand Theft Auto V single-player trainer mod
* Copyright (C) 2019  MAFINS
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*/
#include "ArenaWar.h"

#include "..\..\macros.h"

#include "..\..\Menu\Menu.h"
//#include "..\..\Menu\Routine.h"

#include "..\..\Natives\natives2.h"

#include "TeleLocation.h"
#include "TeleMethods.h"

#include <vector>

namespace sub::TeleportLocations_catind
{
	namespace ArenaWar
	{
#pragma region other arena war locations interior props lists
		const std::vector<PCHAR> x18dlc_int_01{
			"xs_x18int01_light_connector",
			"xs_x18int01_pit_fencedemo_col",
			"xs_x18int01_pit_fenceoval_col",
			"xs_x18int01_pit_fence_closed_col",
			"xs_x18int01_pit_ovala_col001",
			"xs_x18int01_pit_ovalb_col",
			"xs_x18int01_shadowproxy",
			"xs_x18int01_shell",
			//
			"Set_Pit_Fence_Closed",
			"Set_Pit_Fence_Demolition",
			"Set_Pit_Fence_Oval",
			"set_pit_fence_ovala",
			"set_pit_fence_ovalb",
			"Set_Pit_Fence_Wall",
			"set_wall_no_pit",
			"set_centreline_dystopian_05",
			"set_centreline_scifi_05",
			"Set_CentreLine_Wasteland_05",
			"Set_Turrets",
			"set_turrets_scifi",
			"set_turrets_wasteland",
			"Set_Team_Band_A",
			"Set_Team_Band_B",
			"Set_Team_Band_C",
			"Set_Team_Band_D",
			"Set_Lights_atlantis",
			"Set_Lights_evening",
			"Set_Lights_hell",
			"Set_Lights_midday",
			"Set_Lights_morning",
			"Set_Lights_night",
			"set_lights_sfnight",
			"Set_Lights_saccharine",
			"Set_Lights_sandstorm",
			"Set_Lights_storm",
			"Set_Lights_toxic",
			"Set_Dystopian_01",
			"Set_Dystopian_02",
			"Set_Dystopian_03",
			"Set_Dystopian_04",
			"Set_Dystopian_05",
			"Set_Dystopian_06",
			"Set_Dystopian_07",
			"Set_Dystopian_08",
			"Set_Dystopian_09",
			"Set_Dystopian_10",
			"Set_Dystopian_11",
			"Set_Dystopian_12",
			"Set_Dystopian_13",
			"Set_Dystopian_14",
			"Set_Dystopian_15",
			"Set_Dystopian_16",
			"Set_Dystopian_17",
			"Set_Scifi_01",
			"Set_Scifi_02",
			"Set_Scifi_03",
			"Set_Scifi_04",
			"Set_Scifi_05",
			"Set_Scifi_06",
			"Set_Scifi_07",
			"Set_Scifi_08",
			"Set_Scifi_09",
			"Set_Scifi_10",
			"Set_Wasteland_01",
			"Set_Wasteland_02",
			"Set_Wasteland_03",
			"Set_Wasteland_04",
			"Set_Wasteland_05",
			"Set_Wasteland_06",
			"Set_Wasteland_07",
			"Set_Wasteland_08",
			"Set_Wasteland_09",
			"Set_Wasteland_10",
			"Set_Dystopian_Scene",
			"Set_Scifi_Scene",
			"Set_Wasteland_Scene",
			"Set_Crowd_A",
			"Set_Crowd_B",
			"Set_Crowd_C",
			"Set_Crowd_D"
		};

		const std::vector<PCHAR> x18dlc_int_mod{
			"xs_x18intmod_arenalightsdummy",
			"xs_x18intmod_b1_2_elev_01",
			"xs_x18intmod_b1_2_exitdoors_01",
			"xs_x18intmod_b1_ceil_lights",
			"xs_x18intmod_b1_lightpanel",
			"xs_x18intmod_b1_vents",
			"xs_x18intmod_back_bollards",
			"xs_x18intmod_back_bumpers",
			"xs_x18intmod_back_columns",
			"xs_x18intmod_back_decals01",
			"xs_x18intmod_back_decasl06",
			"xs_x18intmod_back_detail",
			"xs_x18intmod_back_elev_01",
			"xs_x18intmod_back_elev_02x",
			"xs_x18intmod_back_frames",
			"xs_x18intmod_back_grill",
			"xs_x18intmod_back_handrail",
			"xs_x18intmod_back_panels",
			"xs_x18intmod_back_signage",
			"xs_x18intmod_back_signage001",
			"xs_x18intmod_back_signage02",
			"xs_x18intmod_back_vents01",
			"xs_x18intmod_bedroom_blocker",
			"xs_x18intmod_bedroom_det",
			"xs_x18intmod_bedroom_det001",
			"xs_x18intmod_bedroom_det002",
			"xs_x18intmod_bedroom_mirror",
			"xs_x18intmod_bedroom_mirror001",
			"xs_x18intmod_bedroom_mirror002",
			"xs_x18intmod_beer_wpn",
			"xs_x18intmod_bleachers",
			"xs_x18intmod_blocker_ground",
			"xs_x18intmod_booth_ben",
			"xs_x18intmod_booth_ben_banners",
			"xs_x18intmod_booth_ben_bench01",
			"xs_x18intmod_booth_ben_int",
			"xs_x18intmod_booth_ben_intdet",
			"xs_x18intmod_booth_combo",
			"xs_x18intmod_booth_def",
			"xs_x18intmod_booth_def_doors",
			"xs_x18intmod_booth_doors01",
			"xs_x18intmod_booth_doors2",
			"xs_x18intmod_booth_wp",
			"xs_x18intmod_booth_wp_int",
			"xs_x18intmod_booth_wp_intdet",
			"xs_x18intmod_booth_wp_lights",
			"xs_x18intmod_booth_wp_lights001",
			"xs_x18intmod_booth_wp_shelf",
			"xs_x18intmod_booth_wp_stdoor",
			"xs_x18intmod_clutter_ben",
			"xs_x18intmod_clutter_ben001",
			"xs_x18intmod_front_beams",
			"xs_x18intmod_front_bollards",
			"xs_x18intmod_front_bumpers01",
			"xs_x18intmod_front_burrito_bits",
			"xs_x18intmod_front_burrito_bits2",
			"xs_x18intmod_front_clutter",
			"xs_x18intmod_front_clutter003",
			"xs_x18intmod_front_clutter004",
			"xs_x18intmod_front_clutter02",
			"xs_x18intmod_front_columns",
			"xs_x18intmod_front_decals003",
			"xs_x18intmod_front_decals004",
			"xs_x18intmod_front_decals01",
			"xs_x18intmod_front_decals02",
			"xs_x18intmod_front_decals_red",
			"xs_x18intmod_front_decals_yell",
			"xs_x18intmod_front_detail",
			"xs_x18intmod_front_doors",
			"xs_x18intmod_front_ducts",
			"xs_x18intmod_front_eqpmnt",
			"xs_x18intmod_front_fanbase003",
			"xs_x18intmod_front_fanbase004",
			"xs_x18intmod_front_fanbase01",
			"xs_x18intmod_front_fanbase02",
			"xs_x18intmod_front_floordec",
			"xs_x18intmod_front_handrail",
			"xs_x18intmod_front_hook",
			"xs_x18intmod_front_panels",
			"xs_x18intmod_front_signage02",
			"xs_x18intmod_front_stairs",
			"xs_x18intmod_front_tyre_01b",
			"xs_x18intmod_front_window",
			"xs_x18intmod_front_wnd_grill",
			"xs_x18intmod_ground_bumpy",
			"xs_x18intmod_high_bed_art",
			"xs_x18intmod_high_end_bed",
			"xs_x18intmod_high_off_car_pics",
			"xs_x18intmod_ind_bed",
			"xs_x18intmod_ind_edge_blnd",
			"xs_x18intmod_ind_off_furn",
			"xs_x18intmod_interior_shell_shad",
			"xs_x18intmod_lamp_bdrm",
			"xs_x18intmod_laptop_web_dec",
			"xs_x18intmod_lightpanel",
			"xs_x18intmod_mod1_style01",
			"xs_x18intmod_mod1_style02",
			"xs_x18intmod_mod1_style02back",
			"xs_x18intmod_mod1_style03",
			"xs_x18intmod_mod1_style03back",
			"xs_x18intmod_mod1_style04",
			"xs_x18intmod_mod1_style04back",
			"xs_x18intmod_mod1_style05",
			"xs_x18intmod_mod1_style05back",
			"xs_x18intmod_mod1_style06back",
			"xs_x18intmod_mod1_style07",
			"xs_x18intmod_mod1_style07back",
			"xs_x18intmod_mod1_style08",
			"xs_x18intmod_mod1_style08back",
			"xs_x18intmod_mod1_style09",
			"xs_x18intmod_mod1_style09back",
			"xs_x18intmod_mod2shell",
			"xs_x18intmod_mod2shell_dum",
			"xs_x18intmod_mod2_b1_bollards",
			"xs_x18intmod_mod2_b1_bumpers",
			"xs_x18intmod_mod2_b1_ceil",
			"xs_x18intmod_mod2_b1_decals",
			"xs_x18intmod_mod2_b1_handrail",
			"xs_x18intmod_mod2_b1_panels",
			"xs_x18intmod_mod2_b1_pillars",
			"xs_x18intmod_mod2_b1_signage",
			"xs_x18intmod_mod2_b1_tanks",
			"xs_x18intmod_mod2_b2_signage001",
			"xs_x18intmod_mod2_b2_tanks",
			"xs_x18intmod_mod2_b_signage",
			"xs_x18intmod_mod2_b_signage02",
			"xs_x18intmod_mod2_det01",
			"xs_x18intmod_mod2_style1",
			"xs_x18intmod_mod2_style2",
			"xs_x18intmod_mod2_style3",
			"xs_x18intmod_mod2_style4",
			"xs_x18intmod_mod2_style5",
			"xs_x18intmod_mod2_style6",
			"xs_x18intmod_mod2_style7",
			"xs_x18intmod_mod2_style8",
			"xs_x18intmod_mod2_style9",
			"xs_x18intmod_mod_shelldum01",
			"xs_x18intmod_office_blocker01",
			"xs_x18intmod_office_det_ind",
			"xs_x18intmod_office_det_ind",
			"xs_x18intmod_office_det_stnd",
			"xs_x18intmod_office_det_tech",
			"xs_x18intmod_office_door003",
			"xs_x18intmod_office_door004",
			"xs_x18intmod_office_door02",
			"xs_x18intmod_office_tab",
			"xs_x18intmod_office_tab_hitec",
			"xs_x18intmod_office_tab_ind",
			"xs_x18intmod_office_tv_stand",
			"xs_x18intmod_office_wpn_safe002",
			"xs_x18intmod_off_bed_light_proxy",
			"xs_x18intmod_off_bed_shadprxy",
			"xs_x18intmod_off_ind_furn",
			"xs_x18intmod_off_light_dummy",
			"xs_x18intmod_off_sign01",
			"xs_x18intmod_seatwallgeo",
			"xs_x18intmod_shadowproxy004",
			"xs_x18intmod_shellmod",
			"xs_x18intmod_shell_back",
			"xs_x18intmod_shell_back_beams",
			"xs_x18intmod_shell_bedrm_ht",
			"xs_x18intmod_shell_bedrm_id",
			"xs_x18intmod_shell_bedrm_st",
			"xs_x18intmod_shell_fence",
			"xs_x18intmod_shell_front",
			"xs_x18intmod_shell_office_ht",
			"xs_x18intmod_shell_office_id",
			"xs_x18intmod_shell_office_st",
			"xs_x18intmod_shower",
			"xs_x18intmod_standard_bed",
			"xs_x18intmod_whiskey_bdrm",
			"xs_x18intmod_wpn_bench_01a",
			"xs_x18intmod_x18_shadow_proxy_w",
			"xs_x18intmod_xmas_base",
			//
			"Set_Int_MOD_SHELL_DEF",
			"Set_Int_MOD2_B1",
			"Set_Int_MOD2_B2",
			"Set_Int_MOD2_B_TINT",
			"Set_Int_MOD_BOOTH_DEF",
			"Set_Int_MOD_BOOTH_BEN",
			"Set_Int_MOD_BOOTH_WP",
			"Set_Int_MOD_BOOTH_COMBO",
			"Set_Int_MOD_BEDROOM_BLOCKER",
			"Set_Int_MOD_CONSTRUCTION_01",
			"Set_Int_MOD_CONSTRUCTION_02",
			"Set_Int_MOD_CONSTRUCTION_03",
			"SET_OFFICE_STANDARD",
			"SET_OFFICE_INDUSTRIAL",
			"SET_OFFICE_HITECH",
			"Set_Mod1_Style_01",
			"Set_Mod1_Style_02",
			"Set_Mod1_Style_03",
			"Set_Mod1_Style_04",
			"Set_Mod1_Style_05",
			"Set_Mod1_Style_06",
			"Set_Mod1_Style_07",
			"Set_Mod1_Style_08",
			"Set_Mod1_Style_09",
			"Set_Mod2_Style_01",
			"Set_Mod2_Style_02",
			"Set_Mod2_Style_03",
			"Set_Mod2_Style_04",
			"Set_Mod2_Style_05",
			"Set_Mod2_Style_06",
			"Set_Mod2_Style_07",
			"Set_Mod2_Style_08",
			"Set_Mod2_Style_09",
			"set_arena_peds",
			"set_arena_no peds",
			"SET_XMAS_DECORATIONS",
			"Set_Int_MOD_TROPHY_CAREER",
			"Set_Int_MOD_TROPHY_SCORE",
			"Set_Int_MOD_TROPHY_WAGEWORKER",
			"Set_Int_MOD_TROPHY_TIME_SERVED",
			"Set_Int_MOD_TROPHY_GOT_ONE",
			"Set_Int_MOD_TROPHY_OUTTA_HERE",
			"Set_Int_MOD_TROPHY_SHUNT",
			"Set_Int_MOD_TROPHY_BOBBY",
			"Set_Int_MOD_TROPHY_KILLED",
			"Set_Int_MOD_TROPHY_CROWD",
			"Set_Int_MOD_TROPHY_DUCK",
			"Set_Int_MOD_TROPHY_BANDITO",
			"Set_Int_MOD_TROPHY_SPINNER",
			"Set_Int_MOD_TROPHY_LENS",
			"Set_Int_MOD_TROPHY_WAR",
			"Set_Int_MOD_TROPHY_UNSTOPPABLE",
			"Set_Int_MOD_TROPHY_CONTACT",
			"Set_Int_MOD_TROPHY_TOWER",
			"Set_Int_MOD_TROPHY_STEP",
			"Set_Int_MOD_TROPHY_PEGASUS",
			"SET_BANDITO_RC",
			"SET_OFFICE_TRINKET_07",
			"SET_OFFICE_TRINKET_06",
			"SET_OFFICE_TRINKET_03",
			"SET_OFFICE_TRINKET_04",
			"SET_OFFICE_TRINKET_02",
			"SET_OFFICE_TRINKET_01"
		};

		const std::vector<PCHAR> x18dlc_int_vip{
			"xs_x18intvip_bar_emissive_tubes",
			"xs_x18intvip_bar_stool",
			"xs_x18intvip_bar_stool001",
			"xs_x18intvip_bar_stool002",
			"xs_x18intvip_bar_stool003",
			"xs_x18intvip_bar_units",
			"xs_x18intvip_blends",
			"xs_x18intvip_cig_holder",
			"xs_x18intvip_edges",
			"xs_x18intvip_elevator_trim",
			"xs_x18intvip_frigid",
			"xs_x18intvip_glass_pans",
			"xs_x18intvip_handrail",
			"xs_x18intvip_int02_desk_choc",
			"xs_x18intvip_lift_door_l",
			"xs_x18intvip_lift_door_l001",
			"xs_x18intvip_lift_door_r",
			"xs_x18intvip_lift_door_r001",
			"xs_x18intvip_lift_frames",
			"xs_x18intvip_main_area_architrave",
			"xs_x18intvip_plant",
			"xs_x18intvip_ref_proxy",
			"xs_x18intvip_roulette_light",
			"xs_x18intvip_rug1",
			"xs_x18intvip_seat_pads",
			"xs_x18intvip_seat_stairs",
			"xs_x18intvip_shadow_sock",
			"xs_x18intvip_shell__steps_em1",
			"xs_x18intvip_sleeves",
			"xs_x18intvip_stairs001",
			"xs_x18intvip_steel_rail_front",
			"xs_x18intvip_stee_rails",
			"xs_x18intvip_supports",
			"xs_x18intvip_test_emiisive",
			"xs_x18intvip_vert_supps",
			"xs_x18intvip_vip_em_tubes006",
			"xs_x18intvip_vip_em_tubes1",
			"xs_x18intvip_vip_em_tubes2",
			"xs_x18intvip_vip_lounge_shell",
			"xs_x18intvip_vip_rings",
			"xs_x18intvip_vip_roul_tab_",
			"xs_x18intvip_vip_roul_tab_emf",
			"xs_x18intvip_vip_seat_002",
			"xs_x18intvip_vip_seat_003",
			"xs_x18intvip_vip_seat_004",
			"xs_x18intvip_vip_seat_005",
			"xs_x18intvip_vip_seat_006",
			"xs_x18intvip_vip_seat_007",
			"xs_x18intvip_vip_seat_008",
			"xs_x18intvip_vip_seat_009",
			"xs_x18intvip_vip_seat_010",
			"xs_x18intvip_vip_seat_011",
			"xs_x18intvip_vip_seat_012",
			"xs_x18intvip_vip_seat_013",
			"xs_x18intvip_vip_seat_014",
			"xs_x18intvip_vip_seat_015",
			"xs_x18intvip_vip_seat_016",
			"xs_x18intvip_vip_seat_017",
			"xs_x18intvip_vip_tab_1",
			"xs_x18intvip_vip_tab_2",
			"xs_x18intvip_vip_tab_3",
			"xs_x18intvip_vip_tab_4",
			"xs_x18intvip_wall_farts",
			"xs_x18intvip_wall_farts2",
			"xs_x18intvip_windows_frames",
			"xs_x18intvip_windows_frames_em",
			"xs_x18intvip_windows_frames_em001",
			"xs_x18intvip_windows_frames_em002",
			"xs_x18intvip_windows_frames_em003",
			"xs_x18intvip_windows_frames_em004",
			"xs_x18intvip_windows_frames_em005",
			//
			"VIP_XMAS_DECS"
		};
#pragma endregion

		const std::vector<TeleLocation> vOtherArenaWarRelatedTeleports
		{
			//TeleLocation("", 0.0f, 0.0f, 0.0f, iplsToLoad, iplsToRemove, interiorProps, true, false, true),
			TeleLocation("xs_arena_interior", 2800.0000f, -3800.0000f, 100.0000f,{ "xs_arena_interior" },{},{}/*x18dlc_int_01*/, true, false, true),
			TeleLocation("xs_arena_interior_mod", 205.0000f, 5180.0000f, -90.0000f,{ "xs_arena_interior_mod" },{},{}/*x18dlc_int_mod*/, true, false, true),
			TeleLocation("xs_arena_interior_mod_2", 170.0000f, 5190.0000f, 10.0000f,{ "xs_arena_interior_mod" },{},{}/*x18dlc_int_mod*/, true, false, true),
			TeleLocation("xs_arena_interior_vip", 2799.5290f, -3930.5390f, 182.3500f,{ "xs_arena_interior_vip" },{},{}/*x18dlc_int_vip*/, true, false, true)
		};

		void Sub_ArenaWar()
		{
			AddTitle("Arena War");

			for (auto& otherTele : vOtherArenaWarRelatedTeleports)
			{
				bool bOtherTelePressed = false;
				AddOption(otherTele.name, bOtherTelePressed); if (bOtherTelePressed)
				{
					TeleMethods::ToTeleLocation241(otherTele);
				}
			}

			// BYO
		}
	}

}



