name: Pre_release

on:
  #workflow_run:
  #  workflows: ["MSBuild"]
  #  types:
  #    - completed
      
  push:
    branches: [ "master", "pre_release" ]
  pull_request:
    branches: [ "master", "pre_release" ]


jobs:
  pre-release:
    permissions: write-all
    name: "Pre Release"
    runs-on: windows-latest

    steps:
      - name: Wait on artifact upload
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          ref: ${{github.ref}}
          check-name: 'Upload a Build Artifact'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          
      - uses: actions/checkout@v3

      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.23.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: msbuild.yml
          workflow_conclusion: success
          #branch: master
          name: MenyooSP
          skip_unpack: true
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Menyoo PC v"
          files: MenyooSP.zip
